/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.StudentController;

/**
 *
 * @author KimAnh
 */
public class pnStudent extends javax.swing.JPanel {

    /**
     * Creates new form pnHomePage
     */
    public pnStudent() {
        initComponents();
        StudentController studentController = new StudentController(tbStudent);
        studentController.createTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        pnAddnew = new javax.swing.JButton();
        pnExport = new javax.swing.JButton();
        scStudent = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfSearch.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        pnAddnew.setBackground(new java.awt.Color(76, 175, 80));
        pnAddnew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnAddnew.setForeground(new java.awt.Color(255, 255, 255));
        pnAddnew.setText("+ Thêm mới");

        pnExport.setBackground(new java.awt.Color(76, 175, 80));
        pnExport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnExport.setForeground(new java.awt.Color(255, 255, 255));
        pnExport.setText("Xuất báo cáo");

        javax.swing.GroupLayout pnTopLayout = new javax.swing.GroupLayout(pnTop);
        pnTop.setLayout(pnTopLayout);
        pnTopLayout.setHorizontalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(pnExport)
                .addGap(28, 28, 28)
                .addComponent(pnAddnew)
                .addContainerGap())
        );
        pnTopLayout.setVerticalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pnAddnew)
                        .addComponent(pnExport))
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTopLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnAddnew, pnExport, tfSearch});

        add(pnTop, java.awt.BorderLayout.PAGE_START);

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scStudent.setViewportView(tbStudent);

        add(scStudent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pnAddnew;
    private javax.swing.JButton pnExport;
    private javax.swing.JPanel pnTop;
    private javax.swing.JScrollPane scStudent;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
